#!/bin/bash

# Variables
dot="$HOME/dotfiles"
HISTCONTROL=ignoreboth

# Exports
export BLOCKSIZE=1k
export CPLUS_INCLUDE_PATH="$HOME/opt/include:$CPLUS_INCLUDE_PATH"
export C_INCLUDE_PATH="$HOME/opt/include:$C_INCLUDE_PATH"
export LD_LIBRARY_PATH="$HOME/opt/lib:$LD_LIBRARY_PATH"
export MANPATH="$HOME/opt/doc:$MANPATH"
export PATH="$HOME/opt/bin:$PATH"
#export PS1=" \[$(tput bold)\e[38;5;1m\][\[\e[38;5;42m\]\!\[\e[38;5;1m\]] \[$(tput sgr0)\e[38;5;4m\][\D{%m/%d/%H:%M:%S}] \[$(tput bold)\e[38;5;223m\]\h:\w \[\e[38;5;7m\]"
#export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# Functions
#function dev() { docker run -it $dev_shell ; }
#function dud() { du -h -d 1 "$@" ; }
#function fif() { grep -rnw "$1" -e "$2" ; }
#function json() { pygmentize -l json "$@" ; }
function l() { exa -l --git $@ ;  }
function la() { exa -a  $@ ;  }
function ll() { exa -l  $@ ;  }
function ls() { exa -l --git  $@ ;  }
function lsai() { -l exa *.{png,jpg,jpeg,gif,bmp} 2>/dev/null ;  }
function lsav() { -l exa *.{mp4,avi,mkv} 2>/dev/null ;  }
function lt() { exa -l  -s modified $@ ;  }
function ltr() { exa -l  -s modified -r $@ ;  }
function lz() { exa -l  -s size $@ ;  }
function lzr() { exa -l  -s size -r $@ ;  }
#function shell() { docker run -it $default_shell ; }
function sl() { ls "$@" ;  }
#function status() { git status "$@" ; }
function tree() { exa -l --git -T "$@" ; } 

# Aliases
#alias ...='cd ../../'                       # Go back 2 directory levels
alias ..='cd ../'                           # Go back 1 directory level
#alias .3='cd ../../../'                     # Go back 3 directory levels
#alias .4='cd ../../../../'                  # Go back 4 directory levels
#alias .5='cd ../../../../../'               # Go back 5 directory levels
#alias .6='cd ../../../../../../'            # Go back 6 directory levels
#alias anon='export HISTFILE=/dev/null'
#alias cd..='cd ../'                         # Go back 1 directory level (for fast typers)
#alias df="df -h $@"
#alias dot="cd $dot"
#alias du='du -h'
alias editvimprofile="vim $HOME/.vimrc"
alias qfind="find . -name "                 # qfind:    Quickly search for file
#alias rd='rm -r "$@"'
#alias recent='ls -tr "$@"'
#alias ~="cd ~"                              # ~:            Go Home
